export const ActionTypes = {
  SET_DISHES: "SET_DISHES",
  SELECT_DISH: "SELECT_DISH",
  INCREMENT_DISH_BY_ONE: "INCREMENT_DISH_BY_ONE",
  DECREMENT_DISH_BY_ONE: "DECREMENT_DISH_BY_ONE",
  REMOVE_SELECTED_DISH: "REMOVE_SELECTED_DISH",
  SELECT_WAITER: "SELECT_WAITER",
  GET_TOTAL: "GET_TOTAL",
  RESET_ALL: "RESET_ALL",
  SAVE_AT_ORDERS: "SAVE_AT_ORDERS",
};
