export const ActionTypes = {
  SET_ROCKETS: "SET_ROCKETS",
  SELECT_ROCKET: "SELECT_ROCKET",
  REMOVE_ROCKET: "REMOVE_ROCKET",
  SET_LAUNCHES: "SET_LAUNCHES",
  SET_LAUNCH: "SET_LAUNCH",
  SELECT_LAUNCH: "SELECT_LAUNCH",
  SET_ASTRONAUTS: "SET_ASTRONAUTS",
  SELECT_ASTRONAUT: "SELECT_ASTRONAUT",
  SET_ROADSTER: "SET_ROADSTER",
};
